owner: MigraineKR
repo: status

sites:
  - name: update.migraine.kr
    url: https://update.migraine.kr/

status-website:
  cname: status.migraine.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | Migraine
  introTitle: "**Status** for Migraine"
  introMessage: 편두통케어 웹모니터
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: News
      href: https://go.migraine.kr/update
    - title: Discord
      href: https://go.migraine.kr/community
