owner: MigraineKR
repo: status

sites:
  - name: update.migraine.kr
    url: https://update.migraine.kr/
  - name: brand.migraine.kr
    url: https://brand.migraine.kr/
  - name: gallery.migraine.kr
    url: https://gallery.migraine.kr/
  - name: go.migraine.kr
    url: https://go.migraine.kr/
  - name: share.migraine.kr
    url: https://share.migraine.kr/
    
status-website:
  cname: status.migraine.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | Migraine Care
  introTitle: "**Status** for Migraine Care"
  introMessage: 편두통케어 웹모니터
  navbar:
    - title: Website
      href: https://www.migraine.kr
    - title: Update
      href: https://go.migraine.kr/Update
    - title: Podcast
      href: https://go.migraine.kr/podcast
    - title: YouTube
      href: https://www.youtube.com/@MigraineKR
    - title: Twitter
      href: https://twitter.com/MigraineKR
    - title: Instagram
      href: https://www.instagram.com/MigraineKR
    - title: Facebook
      href: https://www.facebook.com/MigraineKR
    - title: Community
      href: https://go.migraine.kr/community
